---
- hosts: localhost
  vars_files:
  - '.secrets.yml'
  - 'ansible-sf-automation-vars.yml'

  collections:
    - netapp.elementsw
    - community.vmware

  vars:
    sf_url: "https://{{ elementsw_hostname }}/json-rpc/11.0/"
    item: "{{ volname }}"
    state: present


  tasks:
  - name: Login into vCenter
    uri:
      url: https://{{ vcenter_hostname }}/rest/com/vmware/cis/session
      force_basic_auth: yes
      validate_certs: "{{ validate_vm_certs | default(no) }}"
      method: POST
      user: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
    register: login


  - name: Create New Account
    na_elementsw_account:
       hostname: "{{ elementsw_hostname }}"
       username: "{{ elementsw_username }}"
       password: "{{ elementsw_password }}"
       state: "{{ state | default(present) }}"
       element_username: "{{ account }}"
    register: accountstatus
    when:
      - state == "present"
      

  - name: Get Account Info
    uri:
      url: "{{ sf_url }}"
      method: POST
      validate_certs: "{{ validate_sf_certs | default(False) }}"
      user: "{{ elementsw_username }}"
      password: "{{ elementsw_password }}"
      body: '{"method": "GetAccountByName","params": {"username": "{{ account }}"},"id": 2112}'
      force_basic_auth: yes
      status_code: 200
      body_format: json
      return_content: yes
    register: jsonAccountResults
  #- debug: msg="results printed are {{ jsonAccountResults.json }}"


  - name: Set account ID variable and the volumes that reside within the account
    set_fact:
      account_id={{jsonAccountResults.json.result.account.accountID}}
      VolsInAcc={{jsonAccountResults.json.result.account.volumes}}
    when:
      - jsonAccountResults.json.error is not defined



  - name: Unmount VMFS datastores to ESXi
    vmware_host_datastore:
      hostname: '{{ esxi_hostname }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      datastore_name: '{{ volname }}'
      state: "{{ state | default(present) }}"
    delegate_to: localhost
    when: state == "absent"

  - name: Create or remove data volume
    na_elementsw_volume:
       hostname: "{{ elementsw_hostname }}"
       username: "{{ elementsw_username }}"
       password: "{{ elementsw_password }}"
       state: "{{ state | default(present) }}"
       name: "{{ item }}"
       qos: {minIOPS: "{{ min | default(1000) }}", maxIOPS: "{{ max | default(10000) }}", burstIOPS: "{{ burst | default(100000) }}"}
       account_id: "{{ account }}"
       size: "{{ volsize | default(2048) }}"
       size_unit: gb
       enable512e: True
    register: volumes
  - debug: msg="vol name is {{ volname }}"



  - name: get volume ID and SCSI ID
    uri:
      url: "{{ sf_url }}"
      method: POST
      validate_certs: "{{ validate_sf_certs | default(False) }}"
      user: "{{ elementsw_username }}"
      password: "{{ elementsw_password }}"
      body: '{"method": "ListVolumes","params": {"volumeName": "{{ volname }}", "volumeStatus": "active" },"id": 1}'
      force_basic_auth: yes
      status_code: 200
      body_format: json
      return_content: yes
    register: volResults
  - set_fact:
      volscsiID: "{{ volResults.json.result.volumes | map(attribute='scsiNAADeviceID') | list }}"
      volID: "{{ volResults.json.result.volumes | map(attribute='volumeID') | list }}"
  - debug: msg="vol scsi ID is {{ volscsiID[0] }} and volID is {{ volID }}"
    when: state == "present"


  - name: Create Access group
    na_elementsw_access_group:
       hostname: "{{ elementsw_hostname }}"
       username: "{{ elementsw_username }}"
       password: "{{ elementsw_password }}"
       state: "{{ state | default(present) }}"
       name: "{{ accessgroup }}"
       account_id: "{{ account }}"
    register: results
    when: state == "present"


  - name: Get List of all Access group IDs
    uri:
      url: "{{ sf_url }}"
      method: POST
      validate_certs: "{{ validate_sf_certs | default(False) }}"
      user: "{{ elementsw_username }}"
      password: "{{ elementsw_password }}"
      body: '{"method": "ListVolumeAccessGroups","params": {} ,"id": 2112}'
      force_basic_auth: yes
      status_code: 200
      body_format: json
      return_content: yes
    register: jsonVolAccResults


  - name: Set Volume Access Groups ID for  "{{ accessgroup }}"
    set_fact:
       VolAccGrpID: "{{ item.volumeAccessGroupID }}"
       VolsInAccGrp: "{{ item.volumes }}"
    loop: "{{ jsonVolAccResults.json.result.volumeAccessGroups }}"
    loop_control:
      label: "working on: {{ item.name }}"
    when:
      - item.name == accessgroup



  - name: Remove Access Group "{{accessgroup }}" if empty
    na_elementsw_access_group:
       hostname: "{{ elementsw_hostname }}"
       username: "{{ elementsw_username }}"
       password: "{{ elementsw_password }}"
       state: "{{ state | default(present) }}"
       name: "{{ accessgroup }}"
       account_id: "{{ account }}"
    register: results
    when:
      - state == "absent"
      - VolsInAccGrp | length == 0


  - name: Delete Account "{{ account }}" if empty
    na_elementsw_account:
       hostname: "{{ elementsw_hostname }}"
       username: "{{ elementsw_username }}"
       password: "{{ elementsw_password }}"
       state: "{{ state | default(present) }}"
       element_username: "{{ account }}"
    when:
      - state == "absent"
      - VolsInAcc | length == 0


  - name: Set Volume Access Group
    uri:
      url: "{{ sf_url }}"
      method: POST
      validate_certs: "{{ validate_sf_certs | default(False) }}"
      user: "{{ elementsw_username }}"
      password: "{{ elementsw_password }}"
      body: '{"method": "AddVolumesToVolumeAccessGroup","params": {"volumeAccessGroupID": "{{ VolAccGrpID }}","volumes": {{ volID }} } ,"id": 2112}'
      force_basic_auth: yes
      status_code: 200
      body_format: json
      return_content: yes
    when:
       - state == "present"
       - VolAccGrpID is defined

  - pause:

  - name: Gather iSCSI configuration information of ESXi host
    community.vmware.vmware_host_iscsi_info:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
    register: iscsi_info
    when: state == "present"
  #- debug: msg=" {{ iscsi_info.iscsi_properties.iscsi_name }}"


  - name: Add Inititator to Access Group
    uri:
      url: "{{ sf_url }}"
      method: POST
      validate_certs: "{{ validate_sf_certs | default(False) }}"
      user: "{{ elementsw_username }}"
      password: "{{ elementsw_password }}"
      body: '{"method": "AddInitiatorsToVolumeAccessGroup", "params": {"volumeAccessGroupID": "{{ VolAccGrpID }}", "initiators": ["{{ iscsi_info.iscsi_properties.iscsi_name }}"]}, "id" : 2112}'
      force_basic_auth: yes
      status_code: 200
      body_format: json
      return_content: yes
    register: jsonagupdateResults
    #with_items: "{{ hostIQN }}"
    when:
       - VolAccGrpID is defined
       - state == "present"

  - name: Add a dynamic target to iSCSI config of ESXi
    community.vmware.vmware_host_iscsi:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      esxi_hostname: "{{ esxi_hostname }}"
      iscsi_config:
        vmhba_name: vmhba64
        send_target:
          address: "{{ send_target_address }}"
      state: "{{ state | default(present) }}"

  - name: Rescan HBA's for a given ESXi host and refresh storage system objects
    community.vmware.vmware_host_scanhba:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      esxi_hostname: '{{ esxi_hostname }}'
      refresh_storage: true
    delegate_to: localhost
    when: state == "present"


  - name: Mount VMFS datastores to ESXi
    vmware_host_datastore:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datastore_name: '{{ volname }}'
      datastore_type: 'vmfs'
      vmfs_device_name: 'naa.{{ volscsiID[0] }}'
      vmfs_version: 6
      esxi_hostname: '{{ esxi_hostname }}'
      state: "{{ state | default(present) }}"
    delegate_to: localhost
    when: state == "present"
