---
- hosts: localhost
  vars_files:
  - '.secrets.yml'
  - 'ansible-kp-automation-vars.yml'

  collections:
    - netapp.elementsw
    - community.vmware



  vars:
    state: present
    runme: yes



  tasks:
  - name: Define additional vSwitch variables if using 2-cable VSS
    set_fact:
      vm_vswitch: vSwitch0
      iscsi_vswitch: vSwitch0
      vswitch2_uplink1: "{{ vswitch0_uplink1 }}"
      vswitch2_uplink2: "{{ vswitch0_uplink2 }}"
      vswitch1_uplink1: "{{ vswitch0_uplink1 }}"
      vswitch1_uplink2: "{{ vswitch0_uplink2 }}"
    when:
      - number_of_host_uplinks == 2
      - switch_type == "vss"

  - name: Define additional vSwitch variables if using 6-cable VSS
    set_fact:
      vm_vswitch: vSwitch1
      iscsi_vswitch: vSwitch2
    when:
      - number_of_host_uplinks == 6
      - switch_type == "vss"

  - name: Define additional vSwitch variables if using 2-cable VDS
    set_fact:
      vm_vswitch: "{{ vds_name }}"
      iscsi_vswitch: "{{ vds_name }}"
      vswitch2_uplink1: "{{ vswitch0_uplink1 }}"
      vswitch2_uplink2: "{{ vswitch0_uplink2 }}"
      vswitch1_uplink1: "{{ vswitch0_uplink1 }}"
      vswitch1_uplink2: "{{ vswitch0_uplink2 }}"
    when:
      - number_of_host_uplinks == 2
      - switch_type == "vds"



  - name: Login into vCenter
    uri:
      url: https://{{ vcenter_hostname }}/rest/com/vmware/cis/session
      force_basic_auth: yes
      validate_certs: "{{ validate_vm_certs | default(no) }}"
      method: POST
      user: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
    register: login



  - name: Create Datacenter
    community.vmware.vmware_datacenter:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      datacenter_name: '{{ datacenter_name }}'
      state: "{{ state | default(present) }}"
      validate_certs: "{{ validate_vm_certs | default(no) }}"
    delegate_to: localhost
    register: datacenter_create_result
    when:
      - state == "present"
      - runme is defined
